# Generated by `mix grpc.gen`.
# DO NOT EDIT!

defmodule Question.QuestionService.Service do
  use GRPC.Service, name: "QuestionService"

  rpc :QuestionCall, Question.QuestionRequest, Question.QuestionResponse
end

defmodule Question.QuestionService.Stub do
  use GRPC.Stub, service: Question.QuestionService.Service
end

defmodule Question do
  use Protobuf, """
syntax = "proto3";

service QuestionService {
  rpc QuestionCall(QuestionRequest) returns (QuestionResponse);
}

message QuestionRequest {}

message QuestionResponse {
  string question = 1;
}
  """
end
