export DB_URL="ecto://postgres:postgres@localhost/postgres"
make console CMD="mix ecto.rollback --all"
make console CMD="mix do ecto.create, ecto.migrate"
make console CMD="mix run ./priv/repo/seed.exs"
make console CMD="mix test"
