# Generated by `mix grpc.gen.server`.
# Please implement all functions.
defmodule Question.QuestionService.Server do
  use GRPC.Server, service: Question.QuestionService.Service

  def question_call(question_request, _stream) do
    Question.QuestionResponse.new(question: "ok")
  end

end
